// This file is automatically generated in the original app, but the local dev
// environment may not have Supabase env vars. We keep the real client when the
// vars exist and fall back to a lightweight demo client otherwise so the app
// still boots and the DocShield flow can be exercised locally.
import { createClient, type Session, type User } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

type QueryResult<T> = Promise<{ data: T | null; error: null | { message: string } }>;

type MockState = {
  session: Session | null;
  signedOut: boolean;
  tables: Record<string, any[]>;
  files: Record<string, { fileName: string; content: unknown }>;
};

const STORAGE_KEY = "docshield-mock-supabase-state";
const DEMO_USER_ID = "demo-user";
const DEMO_EMAIL = "demo@acme.com";

function makeDemoUser(email = DEMO_EMAIL, fullName = "DocShield Demo"): User {
  return {
    id: DEMO_USER_ID,
    app_metadata: {},
    user_metadata: { full_name: fullName },
    aud: "authenticated",
    created_at: new Date(0).toISOString(),
    confirmation_sent_at: null,
    recovery_sent_at: null,
    email,
    email_confirmed_at: new Date(0).toISOString(),
    last_sign_in_at: new Date().toISOString(),
    phone: "",
    role: "authenticated",
    updated_at: new Date().toISOString(),
    identities: [],
    factors: [],
  } as User;
}

function makeDemoSession(user = makeDemoUser()): Session {
  return {
    access_token: "mock-access-token",
    refresh_token: "mock-refresh-token",
    expires_in: 3600,
    expires_at: Math.floor(Date.now() / 1000) + 3600,
    token_type: "bearer",
    user,
  };
}

function makeDemoState(): MockState {
  const user = makeDemoUser();
  return {
    session: makeDemoSession(user),
    signedOut: false,
    tables: {
      profiles: [
        {
          user_id: user.id,
          full_name: "DocShield Demo",
          email: user.email,
          job_title: "Security Lead",
          avatar_url: null,
        },
      ],
      company_settings: [
        {
          id: "company-demo",
          user_id: user.id,
          company_name: "Acme Pharma",
          company_website: "https://acme.example",
          company_size: "50-200",
          industry: "Pharma",
          address: "1 Demo Way",
          phone: null,
          company_logo_url: null,
          created_at: new Date(0).toISOString(),
          updated_at: new Date().toISOString(),
        },
      ],
      notification_preferences: [
        {
          id: "prefs-demo",
          user_id: user.id,
          email_notifications: true,
          push_notifications: true,
          bug_updates: true,
          mentions: true,
          weekly_digest: false,
        },
      ],
      invitations: [],
      bugs: [],
      comments: [],
      activity_log: [],
      attachments: [],
    },
    files: {},
  };
}

function canUseStorage() {
  return typeof window !== "undefined" && typeof localStorage !== "undefined";
}

function readState(): MockState {
  if (!canUseStorage()) return makeDemoState();
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) return JSON.parse(raw) as MockState;
  } catch {
    // Ignore corrupted state and fall back to demo data.
  }
  return makeDemoState();
}

function writeState(next: MockState) {
  if (!canUseStorage()) return;
  localStorage.setItem(STORAGE_KEY, JSON.stringify(next));
}

function resetIfSignedOut(state: MockState) {
  if (!state.signedOut && state.session) return state;
  return {
    ...state,
    session: null,
  };
}

function getAuthState() {
  const state = resetIfSignedOut(readState());
  if (!state.session && !state.signedOut) {
    state.session = makeDemoSession();
    state.signedOut = false;
    writeState(state);
  }
  return state;
}

function saveSession(session: Session | null) {
  const current = readState();
  const next = {
    ...current,
    session,
    signedOut: session ? false : true,
  };
  writeState(next);
  return next;
}

function upsertRow(table: string, row: Record<string, any>) {
  const state = readState();
  const rows = [...(state.tables[table] ?? [])];
  const idKey = "id" in row ? "id" : "user_id" in row ? "user_id" : null;
  if (idKey) {
    const index = rows.findIndex((entry) => entry[idKey] === row[idKey]);
    if (index >= 0) rows[index] = { ...rows[index], ...row };
    else rows.push(row);
  } else {
    rows.push(row);
  }
  state.tables[table] = rows;
  writeState(state);
  return row;
}

function filterRows(rows: any[], ops: Array<{ type: string; column: string; value?: any }>) {
  return rows.filter((row) =>
    ops.every((op) => {
      if (op.type === "eq") return row[op.column] === op.value;
      if (op.type === "in") return Array.isArray(op.value) && op.value.includes(row[op.column]);
      return true;
    }),
  );
}

function buildTableBuilder(table: string) {
  const ops: Array<{ type: string; column: string; value?: any }> = [];
  let mode: "select" | "insert" | "update" | "delete" = "select";
  let payload: any = null;
  let orderBy: { column: string; ascending: boolean } | null = null;
  let isSingle = false;
  let isMaybeSingle = false;

  const execute = async () => {
    const state = readState();
    const rows = [...(state.tables[table] ?? [])];

    if (mode === "insert") {
      const items = Array.isArray(payload) ? payload : [payload];
      const nextRows = [...rows];
      items.forEach((item) => {
        const row = { ...item };
        if (!row.id) row.id = `${table}-${Math.random().toString(16).slice(2, 10)}`;
        nextRows.push(row);
      });
      state.tables[table] = nextRows;
      writeState(state);
      return { data: items.length === 1 ? items[0] : items, error: null };
    }

    const filtered = filterRows(rows, ops);
    if (mode === "update") {
      const nextRows = rows.map((row) =>
        ops.every((op) => {
          if (op.type === "eq") return row[op.column] === op.value;
          if (op.type === "in") return Array.isArray(op.value) && op.value.includes(row[op.column]);
          return true;
        })
          ? { ...row, ...payload }
          : row,
      );
      state.tables[table] = nextRows;
      writeState(state);
      return { data: filtered[0] ?? null, error: null };
    }

    if (mode === "delete") {
      state.tables[table] = rows.filter(
        (row) =>
          !ops.every((op) => {
            if (op.type === "eq") return row[op.column] === op.value;
            if (op.type === "in") return Array.isArray(op.value) && op.value.includes(row[op.column]);
            return true;
          }),
      );
      writeState(state);
      return { data: filtered, error: null };
    }

    const ordered = orderBy
      ? [...filtered].sort((a, b) => {
          const left = a[orderBy.column];
          const right = b[orderBy.column];
          if (left === right) return 0;
          return (left > right ? 1 : -1) * (orderBy.ascending ? 1 : -1);
        })
      : filtered;

    if (isSingle) {
      return { data: ordered[0] ?? null, error: null };
    }
    if (isMaybeSingle) {
      return { data: ordered[0] ?? null, error: null };
    }
    return { data: ordered, error: null };
  };

  const builder: any = {
    select() {
      mode = "select";
      return builder;
    },
    insert(value: any) {
      mode = "insert";
      payload = value;
      return builder;
    },
    update(value: any) {
      mode = "update";
      payload = value;
      return builder;
    },
    delete() {
      mode = "delete";
      return builder;
    },
    eq(column: string, value: any) {
      ops.push({ type: "eq", column, value });
      return builder;
    },
    in(column: string, value: any[]) {
      ops.push({ type: "in", column, value });
      return builder;
    },
    order(column: string, options?: { ascending?: boolean }) {
      orderBy = { column, ascending: options?.ascending ?? true };
      return builder;
    },
    single() {
      isSingle = true;
      return execute();
    },
    maybeSingle() {
      isMaybeSingle = true;
      return execute();
    },
    then(onFulfilled: any, onRejected: any) {
      return execute().then(onFulfilled, onRejected);
    },
  };

  return builder;
}

function createMockSupabaseClient() {
  const listeners = new Set<(event: string, session: Session | null) => void>();

  const auth = {
    async getSession() {
      const state = getAuthState();
      return { data: { session: state.session } };
    },
    onAuthStateChange(callback: (event: string, session: Session | null) => void) {
      listeners.add(callback);
      const state = getAuthState();
      queueMicrotask(() => callback(state.session ? "SIGNED_IN" : "SIGNED_OUT", state.session));
      return {
        data: {
          subscription: {
            unsubscribe() {
              listeners.delete(callback);
            },
          },
        },
      };
    },
    async signUp({ email, options }: { email: string; options?: { data?: { full_name?: string } } }) {
      const user = makeDemoUser(email, options?.data?.full_name || email.split("@")[0] || "DocShield Demo");
      const session = makeDemoSession(user);
      saveSession(session);
      upsertRow("profiles", {
        user_id: user.id,
        full_name: options?.data?.full_name || "DocShield Demo",
        email: user.email,
        job_title: "Security Lead",
        avatar_url: null,
      });
      listeners.forEach((listener) => listener("SIGNED_IN", session));
      return { data: { user, session }, error: null };
    },
    async signInWithPassword({ email }: { email: string; password: string }) {
      const user = makeDemoUser(email, email.split("@")[0] || "DocShield Demo");
      const session = makeDemoSession(user);
      saveSession(session);
      listeners.forEach((listener) => listener("SIGNED_IN", session));
      return { data: { user, session }, error: null };
    },
    async signInWithOAuth() {
      const session = makeDemoSession();
      saveSession(session);
      listeners.forEach((listener) => listener("SIGNED_IN", session));
      return { data: { provider: "google" }, error: null };
    },
    async signOut() {
      saveSession(null);
      listeners.forEach((listener) => listener("SIGNED_OUT", null));
      return { error: null };
    },
    async updateUser(_payload: { password?: string }) {
      return { data: { user: getAuthState().session?.user ?? makeDemoUser() }, error: null };
    },
    async setSession(session: Session) {
      saveSession(session);
      listeners.forEach((listener) => listener("SIGNED_IN", session));
      return { data: { session }, error: null };
    },
  };

  const storage = {
    from(bucket: string) {
      return {
        async upload(path: string, file: File | Blob | unknown) {
          const state = readState();
          state.files[`${bucket}/${path}`] = {
            fileName: path.split("/").pop() || path,
            content: file,
          };
          writeState(state);
          return { data: { path }, error: null };
        },
        getPublicUrl(path: string) {
          return { data: { publicUrl: `https://mock.local/storage/${bucket}/${path}` } };
        },
      };
    },
  };

  return {
    auth,
    storage,
    from(table: string) {
      return buildTableBuilder(table);
    },
    rpc() {
      return Promise.resolve({ data: [], error: null });
    },
    channel() {
      return {
        on() {
          return this;
        },
        subscribe() {
          return this;
        },
      };
    },
    removeChannel(channel: unknown) {
      return channel;
    },
  };
}

const realSupabase =
  SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
    ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        },
      })
    : createMockSupabaseClient();

export const supabase = realSupabase as typeof realSupabase & {
  auth: {
    getSession: () => Promise<{ data: { session: Session | null } }>;
    onAuthStateChange: (callback: (event: string, session: Session | null) => void) => {
      data: { subscription: { unsubscribe: () => void } };
    };
    signUp: (payload: { email: string; password?: string; options?: { data?: { full_name?: string } } }) => Promise<{
      data: { user: User; session: Session | null };
      error: null | { message: string };
    }>;
    signInWithPassword: (payload: { email: string; password: string }) => Promise<{
      data: { user: User; session: Session | null };
      error: null | { message: string };
    }>;
    signInWithOAuth: (...args: any[]) => Promise<{ data: unknown; error: null | { message: string } }>;
    signOut: () => Promise<{ error: null | { message: string } }>;
    updateUser: (payload: { password?: string }) => Promise<{
      data: { user: User };
      error: null | { message: string };
    }>;
    setSession: (session: Session) => Promise<{ data: { session: Session }; error: null | { message: string } }>;
  };
};

